<a href="https://colab.research.google.com/github/Brianc88/Python-repaso/blob/main/Practicas_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("Hola mundo")

nombre = "Brian"
edad = 36
altura  = 12.80
es_estudiante = False

print ("Nombre: ",nombre, "Edad:", edad, "Altura:", altura,"Estado", es_estudiante )

Hola mundo
Nombre:  Brian Edad: 36 Altura: 12.8 Estado False


In [ ]:
nombre = input("Digite su nombre")
edad = input("Digite su edad")
print ("Nombre: ",nombre, "Edad:", edad)

KeyboardInterrupt: Interrupted by user

In [ ]:
a = int(input("Digite primer numero"))
b = int(input("digite segund numero"))

print("Suma: ",a + b)
print ("El primero es mayor?:", a>b)
print (a>=0 and b>0)


In [ ]:
from ast import mod
a = int(input("Digite primer numero"))


if a>0 and a % 2==0 :
  print ("el numero es positivo y es par")
elif a<0 and a % 2==0:
  print ("el numero es negativo y es par")
elif a>0 and a % 2!=0:
  print ("el numero es positivo y es impar")
elif a<0 and a % 2!=0:
  print ("el numero es negativo y es impar")
else:
  print ("el numero 0")



In [ ]:
a = 7

for i in range(0,11):
  print (a," x ",i," = ",a * i)
password = 0

while password != "12345":
  password = input(print("Digite contraseña"))

In [ ]:
#Proyecto IMC#
print("Bienvenido a la calculadora IMC")
sw = 1
while sw == 1:
  peso = float(input(print("Digite su peso")))
  altura = float(input(print("Digite su altura")))
  imc = peso / (altura**2)
  print ("Su IMC es: ",imc)
  if imc < 18.5:
    print ("Peso bajo")
  elif imc > 18.5 and imc < 24.9:
    print ("Peso normal")
  elif imc > 25.0 and imc < 29.9:
    print("Sobrepeso")
  else:
    print("Obesidad")
  sw = int(input("Digite: \n1 para continuar /\n0 para salir "))





In [ ]:
##LISTAS

data = [2,4,1,3,5,5]
data.append([1,5])
print(data)
data.remove([1,5])
print(data)
maxi = max(data)
mini = min(data)
largo = len(data)
tipo = type(data)
print("Max: ",maxi," Mini: ",mini," len: ",largo , " Tipo: ",tipo)
#print(sorted(data))


##### EJERCICIOS DE ARITMETICA
suma = 0
for i in data:
  suma = suma + i
print("La suma es:", suma, "\n#########################################################" )

###MAXIMOS Y MINIMOS####
mx = data[0]
mi = data[0]
for i in data:
  if mi > i:
    mi = i
  elif mx < i:
    mx = i

print ("El maximo es: ",mx," El minimo es: ",mi)


In [ ]:

##########DUPLICADOS LISTAS ######################



##def duplicados(data):
data_limpia=[]
data_limpia.append(data[0])
print("data: ", data)


for i in data:
  repetido = False
  for j in data_limpia:
    if i == j:
      repetido = True
      break
  if repetido == False:
      data_limpia.append(i)




print("data Limpia: ", data_limpia)

 ## return data_limpia

##duplicados(data)


### forma mas rapida

for x in data:
  if x not in data_limpia:
    data_limpia.append(x)

print("data Limpia: ", data_limpia)
print("Ultimo elemento de la lista", data_limpia[-1:])

try :
  data.remove(5)
except:
  print("No se encontro el valor")

print("data nueva: ",data)
print(sorted(data))
print("Tres primeros elementos", sorted(data[0:3]))

In [ ]:
#####################INTERMEDIOS#######################
orden = ["Brian", "Liz", "Juan","Sebas"]

print(orden[::-1])

print(list(reversed(orden)))




In [1]:
##################AVANZADOS###########################

numeros = list(range(1,51))
primos = []
print(numeros)
cont = 0


for i in numeros:
  iterador = list(range(1,i+1))
  # print(iterador)
  cont = 0
  for j in iterador:
    if (i % j == 0):
      cont = cont + 1

  if(cont == 2):
      primos.append(i)

print(primos)




primos2 = [n for n in numeros if n > 1 and all(n % i != 0 for i in range(2, int(n**0.5)+1))]
print(primos2)

print((2**0.5)+1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]
2.414213562373095


In [ ]:
#########PALINDROMES##################
palabras = ["oso","casa","radar","sol","reconocer"]
palindromo = []
for i in palabras:
  if i == i[::-1]:
    palindromo.append(i)
print(palindromo)

palabras = ["oso", "casa", "radar", "sol", "reconocer"]
palindromos = [p for p in palabras if p == p[::-1]]
print(palindromos)

In [ ]:
################MATRICES##############################
matriz = []
filas = 3
cols = 3
cont = 1
for i in range(filas):
  fila=[]
  for j in range(cols):
    fila.append(cont)
    cont = cont + 1
  matriz.append(fila)
print(matriz, end = " ")
print()



row = 0
for i in range(len(matriz)):
  print(matriz[i][i])


cont = len(matriz)-1
for i in range(len(matriz)):

  print(matriz[cont-i][cont-i])
  ##cont = cont - 1



n = len(matriz)

for i in range(n):
    print(matriz[i][n - 1 - i], "imprime", end=" ")
    print(n - 1 - i, " rest")
    print (i, " i")

In [ ]:
#######################RETO##########################
notas =[]

for i in range(5):
  notas.append(int(input("Digite nota: ")))

notas.sort()
min(notas)
max(notas)
promedio = sum(notas) / len(notas)

print ("La nota maxima es: ", max(notas), "La nota minima es: ", min(notas), "La nota promedio es: ",promedio, "notas ordenadas: ", notas)


print(notas)

Digite nota: 5
Digite nota: 6
Digite nota: 3
Digite nota: 2
Digite nota: 1
La nota maxima es:  6 La nota minima es:  1 La nota promedio es:  3.4 notas ordenadas:  [1, 2, 3, 5, 6]
[1, 2, 3, 5, 6]


In [ ]:
##################MUTACIONN#######################

x = [1,2,3,4,5,6,9]
y = x
y.append(7)
j = x.copy()
j.append(8)
print(x)
print(y)
print(j)


[1, 2, 3, 4, 5, 6, 9, 7]
[1, 2, 3, 4, 5, 6, 9, 7]
[1, 2, 3, 4, 5, 6, 9, 7, 8]


In [ ]:
cartesiano = [(i, j) for i in range(3) for j in range(2)]
print(cartesiano)

[(0, 0), (0, 1), (1, 0), (1, 1), (2, 0), (2, 1)]


In [ ]:
##########################DICCIONARIOS#################################
persona = {
    "nombre" : "Juan Pablo",
    "Apellodo" : "Caballero",
    "Edad" : "1 mes"

 }
persona2 = {}
persona2 = persona.copy()

persona2["nombre"] ="Brian"
persona2["Apellido"]= "Villamil"
persona2["Edad"] = "36 años"



del persona["Apellodo"]
del persona2["Apellodo"]

"""
print(persona.items()," \n", persona.keys())
persona.values()
print(persona)
"""

print(persona.get("nombre", "Benjamin"))



Juan Pablo


In [135]:
#############################EJERCICIO#################################

ventas = {
    "id":1
    ,"descripcion" : "Portatil"
    ,"marca" : "Lenovo"
    ,"precio" : 5000000.0
}
print(ventas.get("marca", "Lenovo"))
print(ventas)



Lenovo
{'id': 1, 'descripcion': 'Portatil', 'marca': 'Lenovo', 'precio': 5000000.0}


In [ ]:
###########################Ejercicio guiado############################

estudiante = {
    "nombre" : "Brian Caballero"
    ,"edad" : 36
    ,"materias":["Matematicas", "Español", "Sociales"]
}


estudiante["materias"].append("Ingles")
estudiante["edad"] = 30
del estudiante["edad"]
print(estudiante)

{'nombre': 'Brian Caballero', 'materias': ['Matematicas', 'Español', 'Sociales', 'Ingles']}


In [61]:
##from itertools import count
#############################Ejercicio Reto#############################
empleados = [
    {"id" : 1, "nombre" : "Juan Pablo Caballero", "Cargo" : "Ïngeniero de sistemas", "Salario" : 5000000},
    {"id" : 2, "nombre" : "Brian Caballero", "Cargo" : "Jefe De BI", "Salario" : 6000000},
    {"id" : 3, "nombre" : "Benjamin Caballero", "Cargo" : "Jefe De TI", "Salario" : 7000000},
    {"id" : 4, "nombre" : "Sebastian Gonzalez", "Cargo" : "Jefe De Marketing", "Salario" : 8000000},
    {"id" : 5, "nombre" : "Sergio Caballero", "Cargo" : "Medico", "Salario" : 9000000},
    {"id" : 6, "nombre" : "Guillermo Caballero", "Cargo" : "Medico", "Salario" : 9000000},
    {"id" : 7, "nombre" : "Cristian Caballero", "Cargo" : "Medico", "Salario" : 9000000}
]

dic_empleado = {"id" : 8, "nombre" : "Tasio Dominguez Villamil", "Cargo" : "Gerente", "Salario" : 9000000}



def agregarEmpleado(empleados, empleado):
  empleados.append(empleado)



def buscarEmpleado(codigo):
  for i in empleados:
    if i["id"] == codigo:
      return i
      break

def salarioPromedio(empleados):
  total = 0
  for i in empleados:
    total += i["Salario"]
  ##promedio =4 total/len(empleados)
  return total/len(empleados)

#print(salarioPromedio(empleados))

def salarioComprhession(emplados):

  return  sum(i["Salario"] for i in empleados)/len(empleados)

def cargosComprension(empleados):

  cargos = list({i["Cargo"] for i in empleados}) ##El corchete le quita los duplicados y la comprension va desde lo estremo hastan lo interior

  return cargos

def cargos(emppleados):
  cargo =  []
  for i in empleados:
    if i["Cargo"] not in cargo:
      cargo.append(i["Cargo"])
  return cargo


agregarEmpleado(empleados, dic_empleado)
buscarEmpleado(4)
salarioPromedio(empleados)
salarioComprhession(empleados)

cargos(empleados)
#cargosComprension(empleados)


['Ïngeniero de sistemas',
 'Jefe De BI',
 'Jefe De TI',
 'Jefe De Marketing',
 'Medico',
 'Gerente']

In [67]:
##########################CONJUNTOS############################################
clientes_enero = ["Brian", "Carlos", "Luisa", "Connie", "Mery", "Juan Pablo","Benjamin"]
clientes_febrero = ["Brian", "Santiago", "Catalina", "Connie", "Mery", "Juan Pablo","Benjamin"]

set_enero = set(clientes_enero)
set_febrero = set(clientes_febrero)

print("Clientes Repetidos", set_enero & set_febrero)
print("clientes nueos", set_febrero - set_enero)
print("clientes nueos", set_enero - set_febrero)

Clientes Repetidos {'Juan Pablo', 'Mery', 'Brian', 'Connie', 'Benjamin'}
clientes nueos {'Santiago', 'Catalina'}
clientes nueos {'Luisa', 'Carlos'}


In [89]:
################################RETO DEL DIA #################################

empleados = [
    {"id": 1, "nombre": "Ana", "cargo": "Analista"},
    {"id": 2, "nombre": "Luis", "cargo": "Ingeniero"},
    {"id": 3, "nombre": "Sofía", "cargo": "Analista"},
    {"id": 4, "nombre": "Carlos", "cargo": "Gerente"}
]


def validacionSet(id_busqueda):
  Act = True
  for i in empleados:
    cargos = {i["cargo"]for i in empleados},
    nombres = {i["nombre"]for i in empleados}
    id   = {i["id"]  for i in empleados}

  print(id)
  for i in id:
    if id_busqueda not in id:
      Act = False

  if(Act == False):
    print("No se encontro el empleado")
  else:
    print("Se encontro el empleado")


  print("Nombres", nombres)
  print("Cargos", cargos)





validacionSet(2)


{1, 2, 3, 4}
Se encontro el empleado
Nombres {'Carlos', 'Ana', 'Sofía', 'Luis'}
Cargos ({'Ingeniero', 'Analista', 'Gerente'},)


In [25]:
##########################NUMPY###############################

import numpy as np
arr = np.array([1,2,3,4,5])
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])  #Matrices


#print(arr.shape)
print(arr *2)
#print(mat.shape)
"""
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.random.random((2,3)))"""

[ 2  4  6  8 10]


'\nprint(np.zeros((2,3)))\nprint(np.ones((2,3)))\nprint(np.random.random((2,3)))'

In [83]:
####################################EJERCICIOS####################################
import numpy as np


matriz = np.random.randint(50,100, size= (3,3))
matriz2 = np.random.rand(3,3)


print(np.sqrt(matriz))
print(matriz)
################################################################################
listado_numerico = np.arange(1, 11)
print(listado_numerico)
print("eleavados", listado_numerico**2)
print("sumados", np.sum(listado_numerico))
print("pomedio", np.mean(listado_numerico))
print("Cinco pimeros", listado_numerico[:5])
print("Los cinco ultimos", listado_numerico[5:])
print("Todos los pares", listado_numerico[listado_numerico % 2 == 0])
print("todos los pares 2", listado_numerico[1::2] )

[[8.24621125 9.79795897 8.06225775]
 [7.14142843 8.36660027 8.06225775]
 [9.53939201 9.69535971 8.36660027]]
[[68 96 65]
 [51 70 65]
 [91 94 70]]
[ 1  2  3  4  5  6  7  8  9 10]
eleavados [  1   4   9  16  25  36  49  64  81 100]
sumados 55
pomedio 5.5
Cinco pimeros [1 2 3 4 5]
Los cinco ultimos [ 6  7  8  9 10]
Todos los pares [ 2  4  6  8 10]
todos los pares 2 [ 2  4  6  8 10]


In [75]:
######################MINI PROYECTO#############################################
precios = np.random.randint(10000,200001, size = 1000)
cantidad = np.random.randint(1,11, size = 1000)

ventas = precios * cantidad

#print("Ventas totales: ", ventas)
print("| Ventas promedio: ", ventas.mean(), " | Venta maxima: ", ventas.max(), " |Venta minima: ", ventas.min()," |Cantidad maxima: ", cantidad.max() )
print("ventas superiores a 500.000: ", ventas[ventas > 500000])

| Ventas promedio:  581226.775  | Venta maxima:  1944860  |Venta minima:  10229  |Cantidad maxima:  10
ventas superiores a 500.000:  [1483110  751930  588371  999036 1159803  645176  940851  501726  956860
  866058  904232  583398  774355 1241317 1533880  562866  811266  922698
  637524  799204  635201  995360  644826  687420 1015638  637266  714028
 1585970 1872840  588465  527860  736950  728856  857430  676865  567720
 1710680 1027348 1220464  514002  544596  752283  686110  719257 1024562
 1021220  901660  607686  924600  895044  779265  633878 1944860 1518960
 1771785  553995 1355810 1099070 1293552  623590  990878  620610  869620
  645834 1371808 1209568  557829  714700  945770  542170 1840910  699680
  678510 1645668  730425  554130 1491840  769920 1114002  837200  993643
 1335537  562940  856300 1232028  787320  508540  536296  840875 1382250
 1401620  582736 1226288  744336 1109508  735336  613844 1344366  914070
 1902320 1211371  593892  738870  727392  747418  586878  792610

In [96]:
#####################################PANDAS########################################
import pandas as pd
serie = pd.Series([1,2,3,4,5], name ="ventas")

print(serie)


dataframe = {
    "producto" : ["A","B","C","D"],
    "Precio" : [1000,2000,3000,4000],
    "Cantidad" : [1,2,3,4]
}

df = pd.DataFrame(dataframe)
print(df)
print(type(df))

0    1
1    2
2    3
3    4
4    5
Name: ventas, dtype: int64
  producto  Precio  Cantidad
0        A    1000         1
1        B    2000         2
2        C    3000         3
3        D    4000         4
<class 'pandas.core.frame.DataFrame'>


In [132]:
import pandas as pd
import seaborn as sns
data = pd.read_excel("Prestamos.xlsx")
titanic = sns.load_dataset("titanic")

# print(titanic)
# print(titanic.info())
#print(data.head())
#print(data.tail())
print(titanic.describe())

print(titanic["survived"].mean())

sobrevivientes_x_sexo = titanic.groupby("sex")["survived"].mean() * 100
sobrevivientes_x_clase_sexo = titanic.groupby(["pclass","sex"])["survived"].mean()*100
print(sobrevivientes_x_sexo)
print(sobrevivientes_x_clase_sexo)

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200
0.3838383838383838
sex
female    74.203822
male      18.890815
Name: survived, dtype: float64
pclass  sex   
1       female    96.808511
        male      36.885246
2       female    92.105263
        male      15.740741
3       female    50.000000
        male      13.544669
Name: survived, dtype